name: prd

on:
  push:
    branches:
    - main

jobs:
  prd:
    name: prd
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install packages
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    - run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/Shunpoco/shunpoco-dev.git
        npm run build
        npm run add-domain
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}


